import time

print("CIA  hack is currently underway!")
time.sleep(2)
print("Hack is currently at 8% ready")
time.sleep(2)
print("Hack is currently at 10% ready")
time.sleep(3)
print("Hack is currently at 17% ready")
time.sleep(4)
print("Hack is currently at 27% ready")
time.sleep(4)
print("Hack is currently at 34% ready")
time.sleep(3)
print("Hack is currently at 41% ready")
time.sleep(3)
print("Hack is currently at 46% ready")
time.sleep(4)
print("Hack is currently at 50% ready")
time.sleep(3)
print("Hack is currently at 56% ready")
time.sleep(4)
print("Hack is currently at 63% ready")
time.sleep(2)
print("Hack is currently at 70% ready")
time.sleep(3)
print("Hack is currently at 76% ready")
time.sleep(4)
print("Hack is currently at 83% ready")
time.sleep(3)
print("Hack is currently at 92% ready")
time.sleep(2)
print("Hack is currently at 100% ready")
time.sleep(3)
print("The CIA is prepared to be hacked, deployment of hack is ready to be executed.")
time.sleep(5)