import time

print("FBI hack is currently underway!")
time.sleep(2)
print("Hack is currently at 8% ready")
time.sleep(2)
print("Hack is currently at 14% ready")
time.sleep(4)
print("Hack is currently at 27% ready")
time.sleep(4)
print("Hack is currently at 34% ready")
time.sleep(3)
print("Hack is currently at 44% ready")
time.sleep(3)
print("Hack is currently at 53% ready")
time.sleep(4)
print("Hack is currently at 59% ready")
time.sleep(3)
print("Hack is currently at 67% ready")
time.sleep(4)
print("Hack is currently at 77% ready")
time.sleep(2)
print("Hack is currently at 80% ready")
time.sleep(3)
print("Hack is currently at 88% ready")
time.sleep(4)
print("Hack is currently at 93% ready")
time.sleep(3)
print("Hack is currently at 97% ready")
time.sleep(2)
print("Hack is currently at 100% ready")
time.sleep(3)
print("The FBI is ready to be hacked, hack executed and ready to deploy!")
time.sleep(3)