import time

print("NASA hack is currently underway!")
time.sleep(2)
print("Hack is currently at 10% ready")
time.sleep(2)
print("Hack is currently at 17% ready")
time.sleep(4)
print("Hack is currently at 26% ready")
time.sleep(3)
print("Hack is currently at 32% ready")
time.sleep(2)
print("Hack is currently at 43% ready")
time.sleep(3)
print("Hack is currently at 56% ready")
time.sleep(2)
print("Hack is currently at 60% ready")
time.sleep(4)
print("Hack is currently at 69% ready")
time.sleep(2)
print("Hack is currently at 74% ready")
time.sleep(3)
print("Hack is currently at 79% ready")
time.sleep(2)
print("Hack is currently at 83% ready")
time.sleep(4)
print("Hack is currently at 90% ready")
time.sleep(3)
print("Hack is currently at 94% ready")
time.sleep(2)
print("Hack is currently at 100% ready")
time.sleep(3)
print("Hack is ready to be executed & deployed!")
time.sleep(3)