import time

print("Police Department hack is currently underway!")
time.sleep(2)
print("Hack is currently at 10% ready")
time.sleep(2)
print("Hack is currently at 17% ready")
time.sleep(3)
print("Hack is currently at 26% ready")
time.sleep(4)
print("Hack is currently at 31% ready")
time.sleep(4)
print("Hack is currently at 39% ready")
time.sleep(3)
print("Hack is currently at 44% ready")
time.sleep(3)
print("Hack is currently at 49% ready")
time.sleep(4)
print("Hack is currently at 50% ready")
time.sleep(3)
print("Hack is currently at 56% ready")
time.sleep(4)
print("Hack is currently at 62% ready")
time.sleep(2)
print("Hack is currently at 69% ready")
time.sleep(3)
print("Hack is currently at 73% ready")
time.sleep(4)
print("Hack is currently at 79% ready")
time.sleep(3)
print("Hack is currently at 87% ready")
time.sleep(2)
print("Hack is currently at 94% ready")
time.sleep(2)
print("Hack is currently at 100% ready")
time.sleep(3)
print("The Police Department has been successfully hacked, deployment is ready!")
time.sleep(5)