import time

print("Testla hack is currently underway!")
time.sleep(2)
print("Hack is currently at 8% ready")
time.sleep(2)
print("Hack is currently at 16% ready")
time.sleep(3)
print("Hack is currently at 23% ready")
time.sleep(4)
print("Hack is currently at 29% ready")
time.sleep(4)
print("Hack is currently at 34% ready")
time.sleep(3)
print("Hack is currently at 45% ready")
time.sleep(3)
print("Hack is currently at 53% ready")
time.sleep(4)
print("Hack is currently at 59% ready")
time.sleep(3)
print("Hack is currently at 63% ready")
time.sleep(4)
print("Hack is currently at 68% ready")
time.sleep(2)
print("Hack is currently at 72% ready")
time.sleep(3)
print("Hack is currently at 79% ready")
time.sleep(4)
print("Hack is currently at 80% ready")
time.sleep(3)
print("Hack is currently at 87% ready")
time.sleep(2)
print("Hack is currently at 94% ready")
time.sleep(2)
print("Hack is currently at 99% ready")
time.sleep(2)
print("Hack is currently at 100% ready")
time.sleep(3)
print("Every Testla car has been hacked successfully, deployment is ready!")
time.sleep(5)